apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scott-web
  name: scott-web
spec:
  replicas: 10
  selector:
    matchLabels:
      app: scott-web
  template:
    metadata:
      labels:
        app: scott-web
    spec:
      containers:
      - image: httpd:alpine3.19
        name: httpd
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
